 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ip_api_autorizados", type: :request do
  
  # IpApiAutorizado. As you add validations to IpApiAutorizado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      IpApiAutorizado.create! valid_attributes
      get ip_api_autorizados_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ip_api_autorizado = IpApiAutorizado.create! valid_attributes
      get ip_api_autorizado_url(ip_api_autorizado)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ip_api_autorizado_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ip_api_autorizado = IpApiAutorizado.create! valid_attributes
      get edit_ip_api_autorizado_url(ip_api_autorizado)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new IpApiAutorizado" do
        expect {
          post ip_api_autorizados_url, params: { ip_api_autorizado: valid_attributes }
        }.to change(IpApiAutorizado, :count).by(1)
      end

      it "redirects to the created ip_api_autorizado" do
        post ip_api_autorizados_url, params: { ip_api_autorizado: valid_attributes }
        expect(response).to redirect_to(ip_api_autorizado_url(IpApiAutorizado.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new IpApiAutorizado" do
        expect {
          post ip_api_autorizados_url, params: { ip_api_autorizado: invalid_attributes }
        }.to change(IpApiAutorizado, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ip_api_autorizados_url, params: { ip_api_autorizado: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ip_api_autorizado" do
        ip_api_autorizado = IpApiAutorizado.create! valid_attributes
        patch ip_api_autorizado_url(ip_api_autorizado), params: { ip_api_autorizado: new_attributes }
        ip_api_autorizado.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ip_api_autorizado" do
        ip_api_autorizado = IpApiAutorizado.create! valid_attributes
        patch ip_api_autorizado_url(ip_api_autorizado), params: { ip_api_autorizado: new_attributes }
        ip_api_autorizado.reload
        expect(response).to redirect_to(ip_api_autorizado_url(ip_api_autorizado))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ip_api_autorizado = IpApiAutorizado.create! valid_attributes
        patch ip_api_autorizado_url(ip_api_autorizado), params: { ip_api_autorizado: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ip_api_autorizado" do
      ip_api_autorizado = IpApiAutorizado.create! valid_attributes
      expect {
        delete ip_api_autorizado_url(ip_api_autorizado)
      }.to change(IpApiAutorizado, :count).by(-1)
    end

    it "redirects to the ip_api_autorizados list" do
      ip_api_autorizado = IpApiAutorizado.create! valid_attributes
      delete ip_api_autorizado_url(ip_api_autorizado)
      expect(response).to redirect_to(ip_api_autorizados_url)
    end
  end
end
