 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sms_historico_envios", type: :request do
  
  # SmsHistoricoEnvio. As you add validations to SmsHistoricoEnvio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SmsHistoricoEnvio.create! valid_attributes
      get sms_historico_envios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
      get sms_historico_envio_url(sms_historico_envio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sms_historico_envio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
      get edit_sms_historico_envio_url(sms_historico_envio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SmsHistoricoEnvio" do
        expect {
          post sms_historico_envios_url, params: { sms_historico_envio: valid_attributes }
        }.to change(SmsHistoricoEnvio, :count).by(1)
      end

      it "redirects to the created sms_historico_envio" do
        post sms_historico_envios_url, params: { sms_historico_envio: valid_attributes }
        expect(response).to redirect_to(sms_historico_envio_url(SmsHistoricoEnvio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SmsHistoricoEnvio" do
        expect {
          post sms_historico_envios_url, params: { sms_historico_envio: invalid_attributes }
        }.to change(SmsHistoricoEnvio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sms_historico_envios_url, params: { sms_historico_envio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sms_historico_envio" do
        sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
        patch sms_historico_envio_url(sms_historico_envio), params: { sms_historico_envio: new_attributes }
        sms_historico_envio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sms_historico_envio" do
        sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
        patch sms_historico_envio_url(sms_historico_envio), params: { sms_historico_envio: new_attributes }
        sms_historico_envio.reload
        expect(response).to redirect_to(sms_historico_envio_url(sms_historico_envio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
        patch sms_historico_envio_url(sms_historico_envio), params: { sms_historico_envio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sms_historico_envio" do
      sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
      expect {
        delete sms_historico_envio_url(sms_historico_envio)
      }.to change(SmsHistoricoEnvio, :count).by(-1)
    end

    it "redirects to the sms_historico_envios list" do
      sms_historico_envio = SmsHistoricoEnvio.create! valid_attributes
      delete sms_historico_envio_url(sms_historico_envio)
      expect(response).to redirect_to(sms_historico_envios_url)
    end
  end
end
