# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ nome: 'Star Wars' }, { nome: 'Lord of the Rings' }])
#   Character.create(nome: 'Luke', movie: movies.first)

PerfilUsuario.create(nome: "Admin", admin: true)
Usuario.create(nome: "Danilo", email: "danilo@rosi.com", senha: "123456", perfil_usuario_id:  PerfilUsuario.first.id)

=begin
Municipio.create([{nome: "Caimbambo" }, 
				{nome: "Calai"},
				{nome: "Calandula"},
				{nome: "Caluquembe"},
				{nome: "Camacupa"},
				{nome: "Camanongue"},
				{nome: "Cambambe"},
				{nome: "Cambulo"},
				{nome: "Cambundi-Catembo"},
				{nome: "Camucuio"},
				{nome: "Cangandala"},
				{nome: "Caombo"},
				{nome: "Capenda-Camulemba"},
				{nome: "Cassongue"},
				{nome: "Catabola"},
				{nome: "Catchiungo"},
				{nome: "Caungula"},
				{nome: "Cazenga"},
				{nome: "Cazengo"},
				{nome: "Caála"},
				{nome: "Cela"},
				{nome: "Chiange"},
				{nome: "Chibia"},
				{nome: "Chicomba"},
				{nome: "Chinguar"},
				{nome: "Chipindo"},
				{nome: "Chitato"},
				{nome: "Chitembo"},
				{nome: "Chongorói"},
				{nome: "Conda"},
				{nome: "Cuaba Nzogo"},
				{nome: "Cuangar"},
				{nome: "Cuango"},
				{nome: "Cuanhama"},
				{nome: "Cubal"},
				{nome: "Cuchi"},
				{nome: "Cuemba"},
				{nome: "Cuílo"},
				{nome: "Cuimba"},
				{nome: "Cuito Cuanavale"},
				{nome: "Cunda-Dia-Baze"},
				{nome: "Cunhinga"},
				{nome: "Curoca"},
				{nome: "Cuvango"},
				{nome: "Cuvelai"},
				{nome: "Dala"},
				{nome: "Damba"},
				{nome: "Dande"},
				{nome: "Dembos"},
				{nome: "Dirico"},
				{nome: "Ebo"},
				{nome: "Ekunha"},
				{nome: "Ganda"},
				{nome: "Golungo Alto"},
				{nome: "Gonguembo"},
				{nome: "Huambo"},
				{nome: "Humpata"},
				{nome: "Ícolo e Bengo"},
				{nome: "Jamba"},
				{nome: "Kuito"},
				{nome: "Libolo"},
				{nome: "Lobito"},
				{nome: "Londuimbale"},
				{nome: "Longa"},
				{nome: "Longonjo"},
				{nome: "Luacano"},
				{nome: "Luanda"},
				{nome: "Luau"},
				{nome: "Lubalo"},
				{nome: "Lubango"},
				{nome: "Lucala"},
				{nome: "Luchazes"},
				{nome: "Luquembo"},
				{nome: "Léua"},
				{nome: "Macocola"},
				{nome: "Malanje"},
				{nome: "Marimba"},
				{nome: "Massango"},
				{nome: "Matala"},
				{nome: "Mavinga"},
				{nome: "Menongue"},
				{nome: "Moxico"},
				{nome: "Mucaba"},
				{nome: "Mucari"},
				{nome: "Muconda"},
				{nome: "Mungo"},
				{nome: "Mussende"},
				{nome: "M'Banza Kongo"},
				{nome: "Namacunde"},
				{nome: "Nambuangongo"},
				{nome: "Moçâmedes"},
				{nome: "Negage"},
				{nome: "Nharea"},
				{nome: "Noqui"},
				{nome: "N'Zeto"},
				{nome: "Ombadja"},
				{nome: "Pango Aluquém"},
				{nome: "Puri"},
				{nome: "Quela"},
				{nome: "Quibala"},
				{nome: "Quiculungo"},
				{nome: "Quilenda"},
				{nome: "Quilengues"},
				{nome: "Quimbele"},
				{nome: "Quipungo"},
				{nome: "Quirima"},
				{nome: "Quissama"},
				{nome: "Quitexe"},
				{nome: "Rivungo"},
				{nome: "Samba Caju"},
				{nome: "Sanza Pombo"},
				{nome: "Saurimo"},
				{nome: "Seles"},
				{nome: "Songo"},
				{nome: "Soyo"},
				{nome: "Sumbe"},
				{nome: "Tchicala-Tcholoanga"},
				{nome: "Tchindjenje"},
				{nome: "Tômbua"},
				{nome: "Ucuma"},
				{nome: "Uíge"},
				{nome: "Viana"},
				{nome: "Virei"},
				{nome: "Xá-Muteba"}, 
				{nome: "Zombo"}])

Country.create([
	{name_eng: "Afghanistan", name_pt: "Afeganistão", iso2: "AF", bacen: "132" },
	{name_eng: "Albania", name_pt: "Republica da Albânia", iso2: "AL", bacen: "175" },
	{name_eng: "Algeria", name_pt: "Argélia", iso2: "DZ", bacen: "590" },
	{name_eng: "American Samoa", name_pt: "Samoa Americana", iso2: "AS", bacen: "6912" },
	{name_eng: "Andorra", name_pt: "Andorra", iso2: "AD", bacen: "370" },
	{name_eng: "Angola", name_pt: "Angola", iso2: "AO", bacen: "400" },
	{name_eng: "Anguilla", name_pt: "Anguilla", iso2: "AI", bacen: "418" },
	{name_eng: "Antarctica", name_pt: "Antártida", iso2: "AQ", bacen: "3596" },
	{name_eng: "Antigua and Barbuda", name_pt: "Antigua e Barbuda", iso2: "AG", bacen: "434" },
	{name_eng: "Argentina", name_pt: "Argentina", iso2: "AR", bacen: "639" },
	{name_eng: "Armenia", name_pt: "Republica da Armênia", iso2: "AM", bacen: "647" },
	{name_eng: "Aruba", name_pt: "Aruba", iso2: "AW", bacen: "655" },
	{name_eng: "Australia", name_pt: "Austrália", iso2: "AU", bacen: "698" },
	{name_eng: "Austria", name_pt: "Áustria", iso2: "AT", bacen: "728" },
	{name_eng: "Azerbaijan", name_pt: "Republica da Azerbaijão", iso2: "AZ", bacen: "736" },
	{name_eng: "Bahamas", name_pt: "Ilhas Bahamas", iso2: "BS", bacen: "779" },
	{name_eng: "Bahrain", name_pt: "Ilhas Bahrein", iso2: "BH", bacen: "809" },
	{name_eng: "Bangladesh", name_pt: "Bangladesh", iso2: "BD", bacen: "817" },
	{name_eng: "Barbados", name_pt: "Barbados", iso2: "BB", bacen: "833" },
	{name_eng: "Belarus", name_pt: "Republica da Belarus", iso2: "BY", bacen: "850" },
	{name_eng: "Belgium", name_pt: "Bélgica", iso2: "BE", bacen: "876" },
	{name_eng: "Belize", name_pt: "Belize", iso2: "BZ", bacen: "884" },
	{name_eng: "Benin", name_pt: "Benin", iso2: "BJ", bacen: "2291" },
	{name_eng: "Bermuda", name_pt: "Bermuda", iso2: "BM", bacen: "906" },
	{name_eng: "Bhutan", name_pt: "Butão", iso2: "BT", bacen: "1198" },
	{name_eng: "Bolivia", name_pt: "Bolívia", iso2: "BO", bacen: "973" },
	{name_eng: "Bosnia and Herzegowina", name_pt: "Republica da Bósnia-herzegovina", iso2: "BA", bacen: "981" },
	{name_eng: "Botswana", name_pt: "Botsuana", iso2: "BW", bacen: "1015" },
	{name_eng: "Bouvet Island", name_pt: "Ilha Bouvet", iso2: "BV", bacen: "1023" },
	{name_eng: "British Indian Ocean Territory", name_pt: "Território Britânico do Oceano Indico", iso2: "IO", bacen: "7820" },
	{name_eng: "Brunei Darussalam", name_pt: "Brunei", iso2: "BN", bacen: "1082" },
	{name_eng: "Bulgaria", name_pt: "Republica da Bulgária", iso2: "BG", bacen: "1112" },
	{name_eng: "Burkina Faso", name_pt: "Burkina Faso", iso2: "BF", bacen: "310" },
	{name_eng: "Burundi", name_pt: "Burundi", iso2: "BI", bacen: "1155" },
	{name_eng: "Cambodia", name_pt: "Camboja", iso2: "KH", bacen: "1414" },
	{name_eng: "Cameroon", name_pt: "Camarões", iso2: "CM", bacen: "1457" },
	{name_eng: "Canada", name_pt: "Canada", iso2: "CA", bacen: "1490" },
	{name_eng: "Cape Verde", name_pt: "Republica de Cabo Verde", iso2: "CV", bacen: "1279" },
	{name_eng: "Cayman Islands", name_pt: "Ilhas Cayman", iso2: "KY", bacen: "1376" },
	{name_eng: "Central African Republic", name_pt: "Republica Centro-Africana", iso2: "CF", bacen: "6408" },
	{name_eng: "Chad", name_pt: "Chade", iso2: "TD", bacen: "7889" },
	{name_eng: "Chile", name_pt: "Chile", iso2: "CL", bacen: "1589" },
	{name_eng: "China", name_pt: "Republica Popular da China", iso2: "CN", bacen: "1600" },
	{name_eng: "Christmas Island", name_pt: "Christmas, Ilha (Navidad)", iso2: "CX", bacen: "5118" },
	{name_eng: "Cocos (Keeling) Islands", name_pt: "Cocos (Keeling), Ilhas", iso2: "CC", bacen: "1651" },
	{name_eng: "Colombia", name_pt: "Colômbia", iso2: "CO", bacen: "1694" },
	{name_eng: "Comoros", name_pt: "Ilhas Comores", iso2: "KM", bacen: "1732" },
	{name_eng: "Congo", name_pt: "Congo", iso2: "CG", bacen: "1775" },
	{name_eng: "Congo, the Democratic Republic of the", name_pt: "Republica Democrática do Congo", iso2: "CD", bacen: "8885" },
	{name_eng: "Cook Islands", name_pt: "Ilhas Cooks", iso2: "CK", bacen: "1030" },
	{name_eng: "Costa Rica", name_pt: "Costa Rica", iso2: "CR", bacen: "1961" },
	{name_eng: "Cote d`Ivoire", name_pt: "Costa do Marfim", iso2: "CI", bacen: "1937" },
	{name_eng: "Croatia (Hrvatska)", name_pt: "Republica da Croácia", iso2: "HR", bacen: "1953" },
	{name_eng: "Cuba", name_pt: "Cuba", iso2: "CU", bacen: "1996" },
	{name_eng: "Cyprus", name_pt: "Chipre", iso2: "CY", bacen: "1635" },
	{name_eng: "Czech Republic", name_pt: "Republica Tcheca", iso2: "CZ", bacen: "7919" },
	{name_eng: "Denmark", name_pt: "Dinamarca", iso2: "DK", bacen: "2321" },
	{name_eng: "Djibouti", name_pt: "Djibouti", iso2: "DJ", bacen: "7838" },
	{name_eng: "Dominica", name_pt: "Ilha Dominica", iso2: "DM", bacen: "2356" },
	{name_eng: "Dominican Republic", name_pt: "Republica Dominicana", iso2: "DO", bacen: "6475" },
	{name_eng: "East Timor", name_pt: "Timor Leste", iso2: "TL", bacen: "7951" },
	{name_eng: "Ecuador", name_pt: "Equador", iso2: "EC", bacen: "2399" },
	{name_eng: "Egypt", name_pt: "Egito", iso2: "EG", bacen: "2402" },
	{name_eng: "El Salvador", name_pt: "El Salvador", iso2: "SV", bacen: "6874" },
	{name_eng: "Equatorial Guinea", name_pt: "Guine-Equatorial", iso2: "GQ", bacen: "3310" },
	{name_eng: "Eritrea", name_pt: "Eritreia", iso2: "ER", bacen: "2437" },
	{name_eng: "Estonia", name_pt: "Republica da Estonia", iso2: "EE", bacen: "2518" },
	{name_eng: "Ethiopia", name_pt: "Etiópia", iso2: "ET", bacen: "2534" },
	{name_eng: "Falkland Islands (Malvinas)", name_pt: "Falkland (Ilhas Malvinas)", iso2: "FK", bacen: "2550" },
	{name_eng: "Faroe Islands", name_pt: "Ilha Feroe", iso2: "FO", bacen: "2593" },
	{name_eng: "Fiji", name_pt: "Fiji", iso2: "FO", bacen: "8702" },
	{name_eng: "Finland", name_pt: "Finlândia", iso2: "FI", bacen: "2712" },
	{name_eng: "France", name_pt: "França", iso2: "FR", bacen: "2755" },
	{name_eng: "French Guiana", name_pt: "Guiana Francesa", iso2: "GF", bacen: "3255" },
	{name_eng: "French Polynesia", name_pt: "Polinésia Francesa", iso2: "PF", bacen: "5991" },
	{name_eng: "French Southern Territories", name_pt: "Terras Austrais e Antárticas Francesas", iso2: "TF", bacen: "3607" },
	{name_eng: "Gabon", name_pt: "Gabão", iso2: "GA", bacen: "2810" },
	{name_eng: "Gambia", name_pt: "Gambia", iso2: "GM", bacen: "2852" },
	{name_eng: "Georgia", name_pt: "Georgia, Republica da", iso2: "GE", bacen: "2917" },
	{name_eng: "Germany", name_pt: "Alemanha", iso2: "DE", bacen: "230" },
	{name_eng: "Ghana", name_pt: "Gana", iso2: "GH", bacen: "2895" },
	{name_eng: "Gibraltar", name_pt: "Gibraltar", iso2: "GI", bacen: "2933" },
	{name_eng: "Greece", name_pt: "Grécia", iso2: "GR", bacen: "3018" },
	{name_eng: "Greenland", name_pt: "Groenlândia", iso2: "GL", bacen: "3050" },
	{name_eng: "Grenada", name_pt: "Granada", iso2: "GD", bacen: "2976" },
	{name_eng: "Guadeloupe", name_pt: "Guadalupe", iso2: "GP", bacen: "3093" },
	{name_eng: "Guam", name_pt: "Guam", iso2: "GU", bacen: "3131" },
	{name_eng: "Guatemala", name_pt: "Guatemala", iso2: "GT", bacen: "3174" },
	{name_eng: "Guinea", name_pt: "Guine", iso2: "GN", bacen: "3298" },
	{name_eng: "Guinea-Bissau", name_pt: "Guine-Bissau", iso2: "GW", bacen: "3344" },
	{name_eng: "Guyana", name_pt: "Guiana", iso2: "GY", bacen: "3379" },
	{name_eng: "Haiti", name_pt: "Haiti", iso2: "HT", bacen: "3417" },
	{name_eng: "Heard and Mc Donald Islands", name_pt: "Ilha Heard e Ilhas McDonald", iso2: "HM", bacen: "3603" },
	{name_eng: "Holy See (Vatican City State)", name_pt: "Vaticano, Estado da Cidade do", iso2: "VA", bacen: "8486" },
	{name_eng: "Honduras", name_pt: "Honduras", iso2: "HN", bacen: "3450" },
	{name_eng: "Hong Kong", name_pt: "Hong Kong", iso2: "HK", bacen: "3514" },
	{name_eng: "Hungary", name_pt: "Hungria, Republica da", iso2: "HU", bacen: "3557" },
	{name_eng: "Iceland", name_pt: "Islândia", iso2: "IS", bacen: "3794" },
	{name_eng: "India", name_pt: "Índia", iso2: "IN", bacen: "3611" },
	{name_eng: "Indonesia", name_pt: "Indonésia", iso2: "ID", bacen: "3654" },
	{name_eng: "Iran (Islamic Republic of)", name_pt: "Ira, Republica Islâmica do", iso2: "IR", bacen: "3727" },
	{name_eng: "Iraq", name_pt: "Iraque", iso2: "IQ", bacen: "3697" },
	{name_eng: "Ireland", name_pt: "Irlanda", iso2: "IE", bacen: "3751" },
	{name_eng: "Israel", name_pt: "Israel", iso2: "IL", bacen: "3832" },
	{name_eng: "Italy", name_pt: "Itália", iso2: "IT", bacen: "3867" },
	{name_eng: "Jamaica", name_pt: "Jamaica", iso2: "JM", bacen: "3913" },
	{name_eng: "Japan", name_pt: "Japão", iso2: "JP", bacen: "3999" },
	{name_eng: "Jordan", name_pt: "Jordânia", iso2: "JO", bacen: "4030" },
	{name_eng: "Kazakhstan", name_pt: "Cazaquistão, Republica do", iso2: "KZ", bacen: "1538" },
	{name_eng: "Kenya", name_pt: "Quênia", iso2: "KE", bacen: "6238" },
	{name_eng: "Kiribati", name_pt: "Kiribati", iso2: "KI", bacen: "4111" },
	{name_eng: "Korea, Democratic People`s Republic of", name_pt: "Coreia, Republica Popular Democrática da", iso2: "KP", bacen: "1872" },
	{name_eng: "Korea, Republic of", name_pt: "Coreia, Republica da", iso2: "KR", bacen: "1902" },
	{name_eng: "Kuwait", name_pt: "Kuwait", iso2: "KW", bacen: "1988" },
	{name_eng: "Kyrgyzstan", name_pt: "Quirguiz, Republica", iso2: "KG", bacen: "6254" },
	{name_eng: "Lao People`s Democratic Republic", name_pt: "Laos, Republica Popular Democrática do", iso2: "LA", bacen: "4200" },
	{name_eng: "Latvia", name_pt: "Letônia, Republica da", iso2: "LV", bacen: "4278" },
	{name_eng: "Lebanon", name_pt: "Líbano", iso2: "LB", bacen: "4316" },
	{name_eng: "Lesotho", name_pt: "Lesoto", iso2: "LS", bacen: "4260" },
	{name_eng: "Liberia", name_pt: "Libéria", iso2: "LR", bacen: "4340" },
	{name_eng: "Libyan Arab Jamahiriya", name_pt: "Líbia", iso2: "LY", bacen: "4383" },
	{name_eng: "Liechtenstein", name_pt: "Liechtenstein", iso2: "LI", bacen: "4405" },
	{name_eng: "Lithuania", name_pt: "Lituânia, Republica da", iso2: "LT", bacen: "4421" },
	{name_eng: "Luxembourg", name_pt: "Luxemburgo", iso2: "LU", bacen: "4456" },
	{name_eng: "Macau", name_pt: "Macau", iso2: "MO", bacen: "4472" },
	{name_eng: "Macedonia, The Former Yugoslav Republic of", name_pt: "Macedônia, Antiga Republica Iugoslava", iso2: "MK", bacen: "4499" },
	{name_eng: "Madagascar", name_pt: "Madagascar", iso2: "MG", bacen: "4502" },
	{name_eng: "Malawi", name_pt: "Malavi", iso2: "MW", bacen: "4588" },
	{name_eng: "Malaysia", name_pt: "Malásia", iso2: "MY", bacen: "4553" },
	{name_eng: "Maldives", name_pt: "Maldivas", iso2: "MV", bacen: "4618" },
	{name_eng: "Mali", name_pt: "Mali", iso2: "ML", bacen: "4642" },
	{name_eng: "Malta", name_pt: "Malta", iso2: "MT", bacen: "4677" },
	{name_eng: "Marshall Islands", name_pt: "Marshall, Ilhas", iso2: "MH", bacen: "4766" },
	{name_eng: "Martinique", name_pt: "Martinica", iso2: "MQ", bacen: "4774" },
	{name_eng: "Mauritania", name_pt: "Mauritânia", iso2: "MR", bacen: "4880" },
	{name_eng: "Mauritius", name_pt: "Mauricio", iso2: "MU", bacen: "4855" },
	{name_eng: "Mayotte", name_pt: "Mayotte (Ilhas Francesas)", iso2: "YT", bacen: "4898" },
	{name_eng: "Mexico", name_pt: "México", iso2: "MX", bacen: "4936" },
	{name_eng: "Micronesia, Federated States of", name_pt: "Micronesia", iso2: "FM", bacen: "4995" },
	{name_eng: "Moldova, Republic of", name_pt: "Moldávia, Republica da", iso2: "MD", bacen: "4944" },
	{name_eng: "Monaco", name_pt: "Mônaco", iso2: "MC", bacen: "4952" },
	{name_eng: "Mongolia", name_pt: "Mongólia", iso2: "MN", bacen: "4979" },
	{name_eng: "Montserrat", name_pt: "Montserrat, Ilhas", iso2: "MS", bacen: "5010" },
	{name_eng: "Morocco", name_pt: "Marrocos", iso2: "MA", bacen: "4740" },
	{name_eng: "Mozambique", name_pt: "Moçambique", iso2: "MZ", bacen: "5053" },
	{name_eng: "Myanmar", name_pt: "Mianmar (Birmânia)", iso2: "MM", bacen: "930" },
	{name_eng: "Namibia", name_pt: "Namíbia", iso2: "NA", bacen: "5070" },
	{name_eng: "Nauru", name_pt: "Nauru", iso2: "NR", bacen: "5088" },
	{name_eng: "Nepal", name_pt: "Nepal", iso2: "NP", bacen: "5177" },
	{name_eng: "Netherlands", name_pt: "Países Baixos (Holanda)", iso2: "NL", bacen: "5738" },
	{name_eng: "New Caledonia", name_pt: "Nova Caledonia", iso2: "NC", bacen: "5428" },
	{name_eng: "New Zealand", name_pt: "Nova Zelândia", iso2: "NZ", bacen: "5487" },
	{name_eng: "Nicaragua", name_pt: "Nicarágua", iso2: "NI", bacen: "5215" },
	{name_eng: "Niger", name_pt: "Níger", iso2: "NE", bacen: "5258" },
	{name_eng: "Nigeria", name_pt: "Nigéria", iso2: "NG", bacen: "5282" },
	{name_eng: "Niue", name_pt: "Niue, Ilha", iso2: "NU", bacen: "5312" },
	{name_eng: "Norfolk Island", name_pt: "Norfolk, Ilha", iso2: "NF", bacen: "5355" },
	{name_eng: "Northern Mariana Islands", name_pt: "Marianas do Norte", iso2: "MP", bacen: "4723" },
	{name_eng: "Norway", name_pt: "Noruega", iso2: "NO", bacen: "5380" },
	{name_eng: "Oman", name_pt: "Oma", iso2: "OM", bacen: "5568" },
	{name_eng: "Pakistan", name_pt: "Paquistão", iso2: "PK", bacen: "5762" },
	{name_eng: "Palau", name_pt: "Palau", iso2: "PW", bacen: "5754" },
	{name_eng: "Panama", name_pt: "Panamá", iso2: "PA", bacen: "5800" },
	{name_eng: "Papua New Guinea", name_pt: "Papua Nova Guine", iso2: "PG", bacen: "5452" },
	{name_eng: "Paraguay", name_pt: "Paraguai", iso2: "PY", bacen: "5860" },
	{name_eng: "Peru", name_pt: "Peru", iso2: "PE", bacen: "5894" },
	{name_eng: "Philippines", name_pt: "Filipinas", iso2: "PH", bacen: "2674" },
	{name_eng: "Pitcairn", name_pt: "Pitcairn, Ilha", iso2: "PN", bacen: "5932" },
	{name_eng: "Poland", name_pt: "Polônia, Republica da", iso2: "PL", bacen: "6033" },
	{name_eng: "Portugal", name_pt: "Portugal", iso2: "PT", bacen: "6076" },
	{name_eng: "Puerto Rico", name_pt: "Porto Rico", iso2: "PR", bacen: "6114" },
	{name_eng: "Qatar", name_pt: "Catar", iso2: "QA", bacen: "1546" },
	{name_eng: "Reunion", name_pt: "Reunião, Ilha", iso2: "RE", bacen: "6602" },
	{name_eng: "Romania", name_pt: "Romênia", iso2: "RO", bacen: "6700" },
	{name_eng: "Russian Federation", name_pt: "Rússia, Federação da", iso2: "RU", bacen: "6769" },
	{name_eng: "Rwanda", name_pt: "Ruanda", iso2: "RW", bacen: "6750" },
	{name_eng: "Saint Kitts and Nevis", name_pt: "São Cristovão e Neves, Ilhas", iso2: "KN", bacen: "6955" },
	{name_eng: "Saint LUCIA", name_pt: "Santa Lucia", iso2: "LC", bacen: "7153" },
	{name_eng: "Saint Vincent and the Grenadines", name_pt: "São Vicente e Granadinas", iso2: "VC", bacen: "7056" },
	{name_eng: "Samoa", name_pt: "Samoa", iso2: "WS", bacen: "6904" },
	{name_eng: "San Marino", name_pt: "San Marino", iso2: "SM", bacen: "6971" },
	{name_eng: "Sao Tome and Principe", name_pt: "São Tome e Príncipe, Ilhas", iso2: "ST", bacen: "7200" },
	{name_eng: "Saudi Arabia", name_pt: "Arábia Saudita", iso2: "SA", bacen: "531" },
	{name_eng: "Senegal", name_pt: "Senegal", iso2: "SN", bacen: "7285" },
	{name_eng: "Seychelles", name_pt: "Seychelles", iso2: "SC", bacen: "7315" },
	{name_eng: "Sierra Leone", name_pt: "Serra Leoa", iso2: "SL", bacen: "7358" },
	{name_eng: "Singapore", name_pt: "Cingapura", iso2: "SG", bacen: "7412" },
	{name_eng: "Slovakia (Slovak Republic)", name_pt: "Eslovaca, Republica", iso2: "SK", bacen: "2470" },
	{name_eng: "Slovenia", name_pt: "Eslovênia, Republica da", iso2: "SI", bacen: "2461" },
	{name_eng: "Solomon Islands", name_pt: "Salomão, Ilhas", iso2: "SB", bacen: "6777" },
	{name_eng: "Somalia", name_pt: "Somalia", iso2: "SO", bacen: "7480" },
	{name_eng: "South Africa", name_pt: "África do Sul", iso2: "ZA", bacen: "7560" },
	{name_eng: "South Georgia and the South Sandwich Islands", name_pt: "Ilhas Geórgia do Sul e Sandwich do Sul", iso2: "GS", bacen: "2925" },
	{name_eng: "Spain", name_pt: "Espanha", iso2: "ES", bacen: "2453" },
	{name_eng: "Sri Lanka", name_pt: "Sri Lanka", iso2: "LK", bacen: "7501" },
	{name_eng: "St. Helena", name_pt: "Santa Helena", iso2: "SH", bacen: "7102" },
	{name_eng: "St. Pierre and Miquelon", name_pt: "São Pedro e Miquelon", iso2: "PM", bacen: "7005" },
	{name_eng: "Sudan", name_pt: "Sudão", iso2: "SD", bacen: "7595" },
	{name_eng: "Suriname", name_pt: "Suriname", iso2: "SR", bacen: "7706" },
	{name_eng: "Svalbard and Jan Mayen Islands", name_pt: "Svalbard e Jan Mayen", iso2: "SJ", bacen: "7552" },
	{name_eng: "Swaziland", name_pt: "Suazilândia", iso2: "SZ", bacen: "7544" },
	{name_eng: "Sweden", name_pt: "Suécia", iso2: "SE", bacen: "7641" },
	{name_eng: "Switzerland", name_pt: "Suíça", iso2: "CH", bacen: "7676" },
	{name_eng: "Syrian Arab Republic", name_pt: "Síria, Republica Árabe da", iso2: "SY", bacen: "7447" },
	{name_eng: "Taiwan, Province of China", name_pt: "Formosa (Taiwan)", iso2: "TW", bacen: "1619" },
	{name_eng: "Tajikistan", name_pt: "Tadjiquistao, Republica do", iso2: "TJ", bacen: "7722" },
	{name_eng: "Tanzania, United Republic of", name_pt: "Tanzânia, Republica Unida da", iso2: "TZ", bacen: "7803" },
	{name_eng: "Thailand", name_pt: "Tailândia", iso2: "TH", bacen: "7765" },
	{name_eng: "Togo", name_pt: "Togo", iso2: "TG", bacen: "8001" },
	{name_eng: "Tokelau", name_pt: "Toquelau, Ilhas", iso2: "TK", bacen: "8052" },
	{name_eng: "Tonga", name_pt: "Tonga", iso2: "TO", bacen: "8109" },
	{name_eng: "Trinidad and Tobago", name_pt: "Trinidad e Tobago", iso2: "TT", bacen: "8150" },
	{name_eng: "Tunisia", name_pt: "Tunísia", iso2: "TN", bacen: "8206" },
	{name_eng: "Turkey", name_pt: "Turquia", iso2: "TR", bacen: "8273" },
	{name_eng: "Turkmenistan", name_pt: "Turcomenistão, Republica do", iso2: "TM", bacen: "8249" },
	{name_eng: "Turks and Caicos Islands", name_pt: "Turcas e Caicos, Ilhas", iso2: "TC", bacen: "8230" },
	{name_eng: "Tuvalu", name_pt: "Tuvalu", iso2: "TV", bacen: "8281" },
	{name_eng: "Uganda", name_pt: "Uganda", iso2: "UG", bacen: "8338" },
	{name_eng: "Ukraine", name_pt: "Ucrânia", iso2: "UA", bacen: "8311" },
	{name_eng: "United Arab Emirates", name_pt: "Emirados Árabes Unidos", iso2: "AE", bacen: "2445" },
	{name_eng: "United Kingdom", name_pt: "Reino Unido", iso2: "GB", bacen: "6289" },
	{name_eng: "United States", name_pt: "Estados Unidos", iso2: "US", bacen: "2496" },
	{name_eng: "United States Minor Outlying Islands", name_pt: "Ilhas Menores Distantes dos Estados Unidos", iso2: "UM", bacen: "18664" },
	{name_eng: "Uruguay", name_pt: "Uruguai", iso2: "UY", bacen: "8451" },
	{name_eng: "Uzbekistan", name_pt: "Uzbequistão, Republica do", iso2: "UZ", bacen: "8478" },
	{name_eng: "Vanuatu", name_pt: "Vanuatu", iso2: "VU", bacen: "5517" },
	{name_eng: "Venezuela", name_pt: "Venezuela", iso2: "VE", bacen: "8508" },
	{name_eng: "Viet Nam", name_pt: "Vietnã", iso2: "VN", bacen: "8583" },
	{name_eng: "Virgin Islands (British)", name_pt: "Virgens, Ilhas (Britânicas)", iso2: "VG", bacen: "8630" },
	{name_eng: "Virgin Islands (U.S.)", name_pt: "Virgens, Ilhas (E.U.A.)", iso2: "VI", bacen: "8664" },
	{name_eng: "Wallis and Futuna Islands", name_pt: "Wallis e Futuna, Ilhas", iso2: "WF", bacen: "8753" },
	{name_eng: "Western Sahara", name_pt: "Saara Ocidental", iso2: "EH", bacen: "6858" },
	{name_eng: "Yemen", name_pt: "Iémen", iso2: "YE", bacen: "3573" },
	{name_eng: "Yugoslavia", name_pt: "Iugoslávia, República Fed. da", iso2: "YU", bacen: "3883" },
	{name_eng: "Zambia", name_pt: "Zâmbia", iso2: "ZM", bacen: "8907" },
	{name_eng: "Zimbabwe", name_pt: "Zimbabue", iso2: "ZW", bacen: "6653" },
	{name_eng: "Bailiwick of Guernsey", name_pt: "Guernsey, Ilha do Canal (Inclui Alderney e Sark)", iso2: "GG", bacen: "3212" },
	{name_eng: "Bailiwick of Jersey", name_pt: "Jersey, Ilha do Canal", iso2: "JE", bacen: "3930" },
	{name_eng: "Isle of Man", name_pt: "Man, Ilha de", iso2: "IM", bacen: "3595" },
	{name_eng: "Crna Gora (Montenegro)", name_pt: "Montenegro", iso2: "ME", bacen: "4985" },
	{name_eng: "Republika Srbija", name_pt: "Sérvia", iso2: "RS", bacen: "7370" },
	{name_eng: "Republic of South Sudan", name_pt: "Sudao do Sul", iso2: "SS", bacen: "7600" },
	{name_eng: "Zona del Canal de Panamá", name_pt: "Zona do Canal do Panamá", iso2: "NULL", bacen: "8958" },
	{name_eng: "Dawlat Filasṭīn", name_pt: "Palestina", iso2: "PS", bacen: "5780" },
	{name_eng: "Åland Islands", name_pt: "Ilhas de Aland", iso2: "AX", bacen: "153" },
	{name_eng: "Saint Barthélemy", name_pt: "Coletividade de São Bartolomeu", iso2: "BL", bacen: "3598" },
	{name_eng: "Curaçao", name_pt: "Curaçao", iso2: "CW", bacen: "2003" },
	{name_eng: "Saint Martin", name_pt: "Ilha de São Martinho (França)", iso2: "SM", bacen: "6980" },
	{name_eng: "Bonaire", name_pt: "Bonaire", iso2: "AN", bacen: "990" },
	{name_eng: "Antartica", name_pt: "Antartica", iso2: "AQ", bacen: "420" },
	{name_eng: "Heard Island and McDonald Islands", name_pt: "Ilha Herad e Ilhas Macdonald", iso2: "AU", bacen: "3433" },
	{name_eng: "Collectivité de Saint-Barthélemy", name_pt: "Colectividade de São Bartolomeu", iso2: "FR", bacen: "6939" },
	{name_eng: "Sint Maarten (Países Baixos)", name_pt: "Ilha de São Martinho (Países Baixos)", iso2: "SM", bacen: "6998" },
	{name_eng: "Territoire des Terres australes et antarctiques françaises", name_pt: "Território das Terras Austrais e Antárcticas Francesas", iso2: "TF", bacen: "7811" }
])
=end

Provincium.create([
	{nome: "Bengo", capital: "Caxito", area_km2: "31371", population: "356641", image_map: "", country_id: "6" },
	{nome: "Benguela", capital: "Benguela", area_km2: "31788", population: "2231385", image_map: "", country_id: "6" },
	{nome: "Bié", capital: "Kuito", area_km2: "70314", population: "1455255", image_map: "", country_id: "6" },
	{nome: "Cabinda", capital: "Cabinda", area_km2: "7270", population: "716076", image_map: "", country_id: "6"},
	{nome: "Cuando-Cubango", capital: "Menongue", area_km2: "199049", population: "534002", image_map: "", country_id: "6"},
	{nome: "Cuanza Norte", capital: "Ndalatando", area_km2: "24190", population: "443386", image_map: "", country_id: "6" },
	{nome: "Cuanza Sul", capital: "Sumbe", area_km2: "55660", population: "1881873", image_map: "", country_id: "6" },
	{nome: "Cunene", capital: "Ondjiva", area_km2: "89342", population: "990087", image_map: "", country_id: "6" },
	{nome: "Huambo", capital: "Huambo", area_km2: "34274", population: "2019555", image_map: "", country_id: "6" },
	{nome: "Huíla", capital: "Lubango", area_km2: "75002", population: "2497422", image_map: "", country_id: "6" },
	{nome: "Luanda", capital: "Luanda", area_km2: "2418", population: "6945386", image_map: "", country_id: "6" },
	{nome: "Luanda do Norte", capital: "Dundo", area_km2: "102783", population: "862566", image_map: "", country_id: "6" },
	{nome: "Luanda Sul", capital: "Saurimo", area_km2: "45649", population: "537587", image_map: "", country_id: "6" },
	{nome: "Malanje", capital: "Malanje", area_km2: "97602", population: "986363", image_map: "", country_id: "6" },
	{nome: "Moxico", capital: "Luena", area_km2: "223023", population: "758568", image_map: "", country_id: "6" },
	{nome: "Namibe", capital: "Moçâmedes", area_km2: "58137", population: "495326", image_map: "", country_id: "6" },
	{nome: "Uíge", capital: "Uíge", area_km2: "58698", population: "1483118", image_map: "", country_id: "6" },
	{nome: "Zaire", capital: "MBanza Kongo", area_km2: "40130", population: "594428", image_map: "", country_id: "6" }
])


