- hosts: qa
  tasks:
    - name: "Kill webapp"
      ignore_errors: yes
      shell: kill $(lsof -t -i:3001)

    - name: "Kill consumer"
      ignore_errors: yes
      shell: kill $(ps -efa | grep consumer | awk '{print $2;exit}')

    - name: "git pull do repo"
      ignore_errors: yes
      shell: cd PagasoAPP/pgstrans && git pull

    - name: "start apps"
      ignore_errors: yes
      shell: |
        DATE=`date '+%Y-%m-%d %H:%M:%S'`
        echo "PGSTRANS service on QA started at ${DATE}"
        cd /home/pgsadmin/PagasoAPP/pgstrans
        nohup RAILS_ENV=production /home/pgsadmin/.rvm/gems/ruby-2.7.2/bin/rails server --binding=172.26.10.6 -p 3001 & > ~/PagasoAPP/pgstrans/log/start.log
        DATE=`date '+%Y-%m-%d %H:%M:%S'`
        echo "PGSTRANS service on QA started at ${DATE}"
        echo "Ativando o consumidor do servico SQS AWS"
        nohup RAILS_ENV=production /home/pgsadmin/.rvm/gems/ruby-2.7.2/bin/rake sqs:consumer & >> /home/pgsadmin/PagasoAPP/pgstrans/log/sqs_consumer.log
        echo "EOF" 
